Improve test time controller test
ros2/rosbag2 pull request #1012
Opened 2022-05-12 20:52 UTC by Blast545

Should close https://github.com/ros2/rosbag2/issues/992

It's a simple fix for a test that was heavily relying on the the OS not waking up as explained here:
https://github.com/ros2/rosbag2/issues/992#issuecomment-1120111985

This test right before it makes the same assumption: https://github.com/ros2/rosbag2/blob/5fa3a67e79a03206e4e721a7c714caff72966801/rosbag2_cpp/test/rosbag2_cpp/test_time_controller_clock.cpp#L150
But as it haven't failed I decided not to change it with this PR.

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

2022-05-13 03:15 UTC, MichaelOrlov requested changes
@Blast545 Thank you for the PR.
CI build fails due to forgotten 
```cpp
#include <rclcpp/utilities.hpp>
```
Please add it.

2022-05-13 20:45 UTC, Blast545 commented
Checks are passing, running full CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16708)](http://ci.ros2.org/job/ci_linux/16708/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11288)](http://ci.ros2.org/job/ci_linux-aarch64/11288/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17101)](http://ci.ros2.org/job/ci_windows/17101/)

2022-05-14 02:30 UTC, MichaelOrlov approved these changes
Approve!

2022-05-14 02:31 UTC, merged

2023-06-10 01:49 UTC, emersonknapp commented
I know this is over a year old, but I'm adding some context here for future historians: This PR didn't actually do anything to the test - since `rclcpp` is not used in the test, the loop never ran, which means that any spurious wakeup still caused the test to fail. The original 100 nanosecond sleep request test likely never failed because it was very unlikely or maybe even impossible for a spurious wakeup to happen in that time frame. The new loop added in this test, on the other hand, slept for a full second (10 million times longer), which made a spurious wakeup far more likely, and therefore actually made this test far more likely to fail, which is why we've seen it so flaky.