Reduce message spam when topics to be recorded do not exist
ros2/rosbag2 pull request #1018
Opened 2022-05-18 23:43 UTC by ihasdapie

Commits extend lifetime of `TopicFilter` to avoid emitting warning messages on instantiation. `topic_filter.hpp` moved to make it accessible from `recorder.hpp`.

- closes #1011

2022-05-19 04:55 UTC, MichaelOrlov requested changes
@ihasdapie  Thank you for your contribution.
Overall looks good among a couple nitpicks.
Please see my comments.

2022-05-19 04:55 UTC, MichaelOrlov commented on rosbag2_transport/include/rosbag2_transport/recorder.hpp
> +  std::unique_ptr<TopicFilter> topic_filter;
Private member names shall end up with `_` underscore. Please rename `topic_filter` accordingly.
Also please move `topic_filter` declaration to the section where other private members declared. i.e. lines 148-164.

2022-05-19 04:55 UTC, MichaelOrlov commented on rosbag2_transport/include/rosbag2_transport/topic_filter.hpp
> +
Please remove redundant delta i.e. empty spaces

2022-05-19 16:51 UTC, jacobperron approved these changes
LGTM with green CI

2022-05-24 21:44 UTC, jacobperron approved these changes
I think the test failures are unrelated [here's the same Linux failure appearing on last night's nightly](https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/lastBuild/testReport/(root)/projectroot/test_play_services__rmw_fastrtps_cpp/) and the Windows failure appears unrelated to rosbag2.

@MichaelOrlov Could you take another look?

2022-05-25 06:10 UTC, MichaelOrlov commented
@jacobperron I confirm that test failures in [projectroot.test_play_services__rmw_fastrtps_cpp](https://ci.ros2.org/job/ci_linux/16740/testReport/junit/(root)/projectroot/test_play_services__rmw_fastrtps_cpp/) and  https://build.ros2.org/job/Rpr__rosbag2__ubuntu_jammy_amd64/93/testReport/junit/(root)/projectroot/test_play_services__rmw_fastrtps_cpp/ unrelated to the changes in this PR.

Please see my latest analysis for those failures here https://github.com/ros2/rosbag2/pull/1013#issuecomment-1126572618

2022-05-25 20:18 UTC, ihasdapie commented
@MichaelOrlov Can you approve this PR so we can get it merged? Thanks

2022-05-25 22:23 UTC, MichaelOrlov approved these changes

2022-05-25 22:24 UTC, MichaelOrlov commented
@ihasdapie Sure I forgot that I requested changes and haven't approved afterwards.

2022-05-25 22:32 UTC, merged