0.17.0
ros2/rosbag2 pull request #1052
Opened 2022-07-31 00:17 UTC by MichaelOrlov

@clalancette @gbiggs @audrow I'd like to make new `rosbag2` release for `rolling`. 
We have accumulated substantial amount of changes and I think it's already time to release them. 

Though, I am first time doing release. Please correct me or advise if I am doing something wrong.
I have prepared update for change logs and tried to bump minor version to 0.17.0

2022-07-31 21:58 UTC, gbiggs commented
The only comment I have after a quick look over the changelogs is that usually we don't include a second level of bullet points in the changelog files.

2022-08-01 12:05 UTC, jhdcs requested changes
I only saw a very minor grammatical issue. Otherwise this looks good to me!

2022-08-01 12:05 UTC, jhdcs commented on rosbag2_storage/CHANGELOG.rst
> + * Get rid from extra data copying operation on playback via moving data instead to publisher
```suggestion
 * Get rid of extra data copying operation on playback via moving data instead to publisher
```

2022-08-01 12:05 UTC, jhdcs commented on rosbag2_transport/CHANGELOG.rst
> + * Get rid from extra data copying operation on playback via moving data instead to publisher
```suggestion
 * Get rid of extra data copying operation on playback via moving data instead to publisher
```

2022-08-02 00:42 UTC, MichaelOrlov commented
> The only comment I have after a quick look over the changelogs is that usually we don't include a second level of bullet points in the changelog files.

@gbiggs I am guessing that we didn't include a  second level of bullets points because was not aware about important details in listed changes.  And release preparation flow was to run a script, delete all second level bullet points which was actually message body from squashed merge commits.

Though I was the reviewer for every changes in this upcoming release and aware about some details and important changes which are not clear from one line in pull request title. 
I decided to put a bit more details when it would be appropriate and nice to have for final user and added second level bullet items manually.

I've checked how it will be rendered. IMO it doesn't look weird or destructive. I found it to be very useful for final users.
![Screenshot from 2022-08-01 17-27-03](https://user-images.githubusercontent.com/7294722/182266761-ef7d3400-98cf-437d-9056-d8674e21c621.png)

2022-08-03 01:15 UTC, MichaelOrlov commented
@jhdcs I've addressed your comments about grammar.
Could you please verify and approve this PR?

2022-08-03 15:31 UTC, jhdcs approved these changes
Looks good to me!

2022-08-04 22:51 UTC, MichaelOrlov commented
@clalancette @jhdcs Since I didn't get any response in 24 hours. I am going to go ahead and merge this PR.

2022-08-05 01:48 UTC, merged

2022-08-05 03:22 UTC, MichaelOrlov commented
@clalancette @audrow I've tried to make release with bloom, however got error message about insufficient rights

```
bloom-release --rosdistro rolling rosbag2
ROS Distro index file associate with commit '0fa1904294ab891b243e231f14de8a995f3de3f9'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/0fa1904294ab891b243e231f14de8a995f3de3f9/index-v4.yaml'
==> Fetching 'rosbag2' repository from 'https://github.com/ros2-gbp/rosbag2-release.git'
Cloning into '/tmp/tmpwmey0xif'...
remote: Enumerating objects: 55104, done.
remote: Counting objects: 100% (4032/4032), done.
remote: Compressing objects: 100% (2947/2947), done.
remote: Total 55104 (delta 1181), reused 3676 (delta 944), pack-reused 51072
Receiving objects: 100% (55104/55104), 8.50 MiB | 6.60 MiB/s, done.
Resolving deltas: 100% (18329/18329), done.
==> Testing for push permission on release repository
==> git remote -v
origin	git@github.com:ros2-gbp/rosbag2-release.git (fetch)
origin	git@github.com:ros2-gbp/rosbag2-release.git (push)
==> git push --dry-run
ERROR: Permission to ros2-gbp/rosbag2-release.git denied to MichaelOrlov.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
It seems that I need to be in [ros2-gbp/rosbag2](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/rosbag2.tf) team to have permissions to push in those git repo.

I have created https://github.com/ros2-gbp/ros2-gbp-github-org/issues/90 with request to join `rosbag2` release team.