rosbag2_py: expose metadata for Reader, fix metadata fields to yield rclpy.Time and Duration values
ros2/rosbag2 pull request #1082
Opened 2022-09-08 19:58 UTC by emersonknapp

2022-09-16 21:19 UTC, MichaelOrlov requested changes
@emersonknapp Overall looks good among forgotten `custom_data` field binding and default initialization from `BagMetadata` structure.

2022-09-16 21:19 UTC, MichaelOrlov commented on rosbag2_py/src/rosbag2_py/_storage.cpp
> +    pybind11::arg("compression_mode") = "")
@emersonknapp Could you please binding and default initialization for `pybind11::arg("custom_data")`?

https://github.com/ros2/rosbag2/blob/50e28cbab7e1cbe227b64a14b721793f6bd57216/rosbag2_storage/include/rosbag2_storage/bag_metadata.hpp#L56

2022-09-23 01:00 UTC, emersonknapp commented
Added a test suite to try out all these constructors, and fixed up usability issues I found along the way. Added missing fields

2022-09-23 17:02 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/c086e5ec5c7c89f6f88a26661d471f6a/raw/4c2a74b859d494154d60e970f99f14e653060561/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_py
TEST args:  --packages-above rosbag2_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10867
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17362)](http://ci.ros2.org/job/ci_linux/17362/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11896)](http://ci.ros2.org/job/ci_linux-aarch64/11896/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17865)](http://ci.ros2.org/job/ci_windows/17865/)

2022-09-23 23:47 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/b386ec8bc1f8bca4fc58810a9ae0db98/raw/4c2a74b859d494154d60e970f99f14e653060561/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_py
TEST args:  --packages-above rosbag2_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10871
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17366)](http://ci.ros2.org/job/ci_linux/17366/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11900)](http://ci.ros2.org/job/ci_linux-aarch64/11900/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17869)](http://ci.ros2.org/job/ci_windows/17869/)

2022-09-28 07:51 UTC, MichaelOrlov approved these changes
LGTM with green CI.

2022-09-28 07:56 UTC, MichaelOrlov commented
Weird failure on Windows CI job. It looks like unrelated.
Trying to re-run Windows job one more time.
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17908)](http://ci.ros2.org/job/ci_windows/17908/)

2022-09-29 02:18 UTC, MichaelOrlov commented
@ros-pull-request-builder retest this please

2022-09-29 19:34 UTC, merged

2023-06-24 02:11 UTC, emersonknapp commented
@mergifyio backport humble