Add plugin comparison benchmark
ros2/rosbag2 pull request #1106
Opened 2022-09-30 04:24 UTC by james-rms

Fixes #1092

2022-09-30 05:55 UTC, james-rms commented on rosbag2_performance/rosbag2_storage_plugin_comparison/src/single_benchmark.cpp
> +///  ./single_benchmark "$(cat your_config.yaml)" /tmp/some_bagfile_filename.bag > results.csv
```suggestion
///  ./single_benchmark "$(cat your_config.yaml)" /tmp/some_existing_temp_dir > results.csv
```

2022-10-04 03:54 UTC, jhurliman commented on rosbag2_performance/rosbag2_storage_plugin_comparison/README.md
> +ros2 pkg run rosbag2_storage_plugin_comparison sweep.py results.csv
```suggestion
ros2 run rosbag2_storage_plugin_comparison sweep.py results.csv
```

2022-10-17 23:03 UTC, james-rms commented
@MichaelOrlov is this something you'd be interested in reviewing? (I can't add reviewers to PRs in this repo)

2022-10-19 22:07 UTC, MichaelOrlov commented
@james-rms Yes, I will take a look on it. Although I need some time for review. 
It seems a lot of new code.

2023-04-01 01:36 UTC, MichaelOrlov requested changes
@james-rms Thanks for your hard work. This is something what is nice to have in our rosbag2 bench-marking packages portfolio.
I haven't finished yet reviewing `single_benchmark.cpp`, however I am getting comeplation errors:
```
--- stderr: rosbag2_storage_plugin_comparison                                      
/home/morlov/ros2_rolling/src/ros2/rosbag2/rosbag2_performance/rosbag2_storage_plugin_comparison/src/single_benchmark.cpp: In constructor ‘BaselineStat::BaselineStat()’:
/home/morlov/ros2_rolling/src/ros2/rosbag2/rosbag2_performance/rosbag2_storage_plugin_comparison/src/single_benchmark.cpp:169:22: error: variable ‘BaselineStat::BaselineStat()::mallinfo2 info’ has initializer but incomplete type
  169 |     struct mallinfo2 info = mallinfo2();
      |                      ^~~~
/home/morlov/ros2_rolling/src/ros2/rosbag2/rosbag2_performance/rosbag2_storage_plugin_comparison/src/single_benchmark.cpp:169:39: error: invalid use of incomplete type ‘struct BaselineStat::BaselineStat()::mallinfo2’
  169 |     struct mallinfo2 info = mallinfo2();
      |                                       ^
```
Do you have any ideas why? Or how to workaround or fix this error?

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_compression_comparison/storage_config/chunk_compressed.yaml
> +compression: "Zstd"
@james-rms It will be better to explicitly specify `chunkSize` here.  
Default chunk size could be changed between mcap versions. I would not rely on it.

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/CMakeLists.txt
> +  set(ament_cmake_cpplint_FOUND TRUE)
What was a rational for skipping copyright checker and cpplint ?
It seems you have a valid copyright blocks.
I would recommend to enable them.

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/README.md
> +| plugin_config |    |  The name of the "plugin_config" parameter variant used for this run. |
| plugin_config | - appeared twice in the table. Expected to be only once.

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/package.xml
> +  <license>MIT</license>
Why `MIT` license in package.xml, although `Apache v2.0` in `.cpp/.hpp` files.
Can you please change license to the `Apache v2.0` ?

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/README.md
> +is measured just before allocating a Writer instance. all memory usage values include the memory allocated
```suggestion
is measured just before allocating a Writer instance. All memory usage values include the memory allocated
```

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/scripts/sweep.py
> +CONFIG_DIMENSIONS = {
It will be more user friendly if move out all config specific parameters in dedicated yaml config file.
However it could be in a follow up PR.

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/scripts/sweep.py
> +        "large": { "topics": [{"name": "/large", "message_size": 1_000_000}]},
I would recommend to increase default size for `"large"` messages. 
Regular use case is FulHD camera stream 1920x1080x3=622080 bytes

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/scripts/sweep.py
> +                "compression": "None",
I would recommend to add explicitly parameter
"noChuncking": False

2023-04-01 01:36 UTC, MichaelOrlov commented on rosbag2_performance/rosbag2_storage_plugin_comparison/scripts/sweep.py
> +        name_dict.get("batch_size", "") in ["medium", "large"]
Could you please explain why we need to ignore such configurations?

2023-12-14 06:57 UTC, MichaelOrlov commented
- Closing as stale PR with no response from the author for a long time. 
- Feel free to reopen if it will be updates on it.

2023-12-14 06:57 UTC, closed without merging