feat(rosbag2_cpp): Add SplitBagfile recording service.
ros2/rosbag2 pull request #1115
Opened 2022-10-05 01:50 UTC by rshanor

Fixes https://github.com/ros2/rosbag2/issues/1087

Tested from the command line and verified that below command closed one log file and opened another

ros2 service call /rosbag2_recorder/split_bagfile
rosbag2_interfaces/srv/SplitBagfile

Signed-off-by: Rick Shanor <rickshanor@gmail.com>

2022-10-05 01:51 UTC, rshanor commented
@MichaelOrlov is this what you had in mind?

2022-10-05 03:39 UTC, MichaelOrlov requested changes
@rshanor Thanks for implementation. Yes it looks very close to my proposal among a few nitpicks see them in inline comments.

We also need to add coverage in unit tests for newly exposed API.
To add coverage on `SequentialWriter` level perhaps we can reuse existing tests just need to alter them a bit to call `split_bagfiles` explicitly.
Will need to replace `ManualSplitWriter` with `rosbag2_cpp::writers::SequentialWriter` here
https://github.com/ros2/rosbag2/blob/c92010b00f894418c7b3fed45866f1ef91df706a/rosbag2_cpp/test/rosbag2_cpp/test_sequential_writer.cpp#L595
And call `writer.split_bagfile()` here
https://github.com/ros2/rosbag2/blob/c92010b00f894418c7b3fed45866f1ef91df706a/rosbag2_cpp/test/rosbag2_cpp/test_sequential_writer.cpp#L612

BTW we don't need `ManualSplitWriter` any more please delete it.

As regards to the integration tests for checking service call on transport layer there are will be a bit more work. 
Will need to add new test in https://github.com/ros2/rosbag2/blob/rolling/rosbag2_transport/test/rosbag2_transport/test_record_services.cpp similar way as `trigger_snapshot` test implemented.
https://github.com/ros2/rosbag2/blob/c92010b00f894418c7b3fed45866f1ef91df706a/rosbag2_transport/test/rosbag2_transport/test_record_services.cpp#L140-L154

May need to parametrize `storage_options_.snapshot_mode` for new unit test.
https://github.com/ros2/rosbag2/blob/c92010b00f894418c7b3fed45866f1ef91df706a/rosbag2_transport/test/rosbag2_transport/test_record_services.cpp#L71

Also please correct DCO signature. Our checker giving following error:
> Commit sha: [5e5679e](https://github.com/ros2/rosbag2/pull/1115/commits/5e5679edc83dd9182fe7386ba5f54d2311f6828b), Author: Rick Shanor, Committer: Rick Shanor; Expected "Rick Shanor [rick@hadrian.co](mailto:rick@hadrian.co)", but got "Rick Shanor [rickshanor@gmail.com](mailto:rickshanor@gmail.com)".

2022-10-05 17:23 UTC, rshanor reviewed
@MichaelOrlov I think I addressed all your PR comments and I added some test coverage. Thank you for the feedback.

The  RecordFixture.record_end_to_end_test_with_zstd_file_compression tests were failing locally for me, but I think that is unrelated to my change.

2022-10-06 08:02 UTC, emersonknapp commented
Just as a note here (which is not to block the review at all), the services tests are unfortunately very flaky and therefore not relied on in the main CI. If you happen to have any ideas how to make them deterministic, which they currently are not, then that improvement would be greatly appreciated. However, we shouldn't block an improvement on preexisting bad infrastructure.

2022-10-06 15:55 UTC, rshanor commented
@emersonknapp interesting. Are all the service tests flaky or just some of them? The test I added should be totally deterministic I think (just call a service once and make sure it returns).

2022-10-06 17:40 UTC, rshanor commented
Thanks for the link, but ya I dont think I have time to dig into that at the moment.

I am new to ROS2 and DDS but have been able to write some pretty complicated (5+ node pick and place simulation) integration tests using the launch_testing package to test service interfaces without much flakiness.

ACK you comment on sleeps. Its not strictly necessary for these tests. I mostly just copy-pasted from the above node to let the recorder do something. All my test checks is that SplitBagfile is called and that some bool in the recorder is set appropriately.

2022-10-06 19:38 UTC, emersonknapp approved these changes
This LGTM

One non-blocking thing I would appreciate is removing `ManualSplitSequentialWriter` from https://github.com/ros2/rosbag2/blob/rolling/rosbag2_cpp/test/rosbag2_cpp/fake_data.hpp#L23 now that the method is truly public.

2022-10-06 19:55 UTC, rshanor commented
> One non-blocking thing I would appreciate is removing `ManualSplitSequentialWriter` from https://github.com/ros2/rosbag2/blob/rolling/rosbag2_cpp/test/rosbag2_cpp/fake_data.hpp#L23 now that the method is truly public.

Removed!

2022-10-06 19:59 UTC, rshanor commented
@MichaelOrlov PTAL when you get a chance. Thanks!

Side question, how frequently are changes pushed to ROS Index? How long will I need to build from source to access these changes in humble?

2022-10-06 23:45 UTC, emersonknapp approved these changes

2022-10-06 23:55 UTC, emersonknapp commented
Well - this code is going into the head Rolling branch - it won't go to Humble at all unless we take additional steps.

One caveat before mentioning the process: We try to maintain API/ABI stability within a released ROS distribution. This PR only adds _new_ APIs, which is fine for API stability, it's non-breaking. I do worry though that based on the nature of the change it may not be ABI stable, that's very hard to guarantee whenever changing any class signatures. Part of me wants to avoid breaking that, however `rosbag2` has not yet reached a point where it explicitly makes that hard guarantee within a distro. So, we can get away with breaking ABI, and probably shouldn't wring our hands too much about it (talking to myself mostly here) given the relative immaturity of the rosbag2 project and the usability improvements that can be gained by adding these new features.

That said, to get this into Humble, once it is merged, we need to:
* Create a backport PR cherry-picking the changes onto the `humble` branch. This is semi-automatable via the mergify bot, and I can run that command once we're ready.
* Once change is merged, bump version number and `bloom` a new release to Humble
* Wait for the next Humble sync following the release (changes will immediately start being built into [ros2-testing apt repo](http://packages.ros.org/ros2-testing/), when the release apt repositories are synced to newer versions. This happens every 2 months or so, it's a little irregular cadence

2022-10-07 06:18 UTC, MichaelOrlov commented
@rshanor I am sorry for the delay I didn't have time to reiterate on code review.
I will try to find time at Friday PST.

From quick view on the test. I agree it's going to be flaky. Usually if test rely on some unconditional sleep inside, it is 99.99% probability that it will be flaky on CI. 
Also since in these two lines
```
successful_service_request<SplitBagfile>(cli_split_bagfile_);
EXPECT_TRUE(mock_writer.split_bagfile_called());
```
service request delivery may be asynchronous and `EXPECT_TRUE(mock_writer.split_bagfile_called());` may fail due to some delays on CI.
I agree with @emersonknapp that need to find some deterministic way: 
1. How to confirm that recording actually has been started to be ready to send request. 
2. Check that split bag happened more robustly. Perhaps by registering some callbacks with gtest infrastructure or checking that splited files exists on filesystem in temp folder.

I might will have some better ideas when I will look on it more closely.

BTW other unit tests with services mostly flaky in rosbag2 player and when the same service requests sending repeatedly in short time. Also those issue reproduces on all 3 DDS vendors and unlikely to be related to the DDS implementation.

2022-10-10 08:40 UTC, MichaelOrlov requested changes
@rshanor Thanks for your contribution. 
Even though the tests not fully deterministic, I am inclined to move forward and merge them as is. I will create follow up PR with `record_services` tests redesign to make them more deterministic and running in shorter time.
Please remove sleep in split test.
Also please rebase your branch on top of latest `rolling` branch. We have braking changes in another packages which causing failure in tests. 
Those failures most probably unrelated to your changes but we need to be assure.

2022-10-10 08:40 UTC, MichaelOrlov commented on rosbag2_transport/test/rosbag2_transport/test_record_services.cpp
> +  std::this_thread::sleep_for(duration);
Please remove this sleep. 
We publishing for 2.5 seconds, it should be enough to receive at least on message needed for split.

2022-10-10 12:36 UTC, clalancette commented
> Even though the tests not fully deterministic,

We'd really prefer if we don't have known flaky tests.  They make it difficult for us to run CI on every single package, since we have to keep some kind of list of "known flaky" tests, and then ignore those.  It means that other regressions fall through the cracks, since people see a yellow CI, think "this is probably known flaky", and then merge.  It also means that external contributors get confused by yellow CI tests.

If you want to move forward with this regardless, I'll suggest at least marking the known flaky tests as xfail for now.  That way they won't be run at all, and won't affect all upstream and downstream packages.

2022-10-10 19:16 UTC, MichaelOrlov commented
@clalancette We don't know yet if it's going to be flay or not on CI. It's just tend to be flaky.  But it didn't fail yet.
At the end it's not going to be significantly more flaky than existent tests in the same file. It's more generic problem.

@rshanor Could you please add `xfail` label for `test_record_services` tests in CMake.txt file?
I will remove this label when will submit followup PR with redesign in those unit tests.
Will need to add `ament_add_test_label(test_record_services xfail)` right after
https://github.com/rshanor/rosbag2/blob/78f391210317318a862b5eea434e1c7732df700a/rosbag2_transport/CMakeLists.txt#L229-L232

2022-10-10 19:47 UTC, rshanor commented
> Could you please add `xfail` label for `test_record_services` tests in CMake.txt file?

Done

2022-10-10 19:56 UTC, rshanor commented
> Also please rebase your branch on top of latest `rolling` branch. We have braking changes in another packages which causing failure in tests.

Done

2022-10-10 21:32 UTC, MichaelOrlov commented
Gist: https://gist.githubusercontent.com/MichaelOrlov/0f53de688de23ccfcd61b54f67af1b7e/raw/35a8cd055cb943c4d6a1e6107b731767677094f7/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_cpp rosbag2_transport rosbag2_tests
TEST args:  --packages-above rosbag2_cpp rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10965
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17471)](http://ci.ros2.org/job/ci_linux/17471/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12000)](http://ci.ros2.org/job/ci_linux-aarch64/12000/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18011)](http://ci.ros2.org/job/ci_windows/18011/)

2022-10-11 00:37 UTC, MichaelOrlov commented
@clalancette I need your attention to test failures in `ros2bag`.
We didn't touched `ros2bag` nor any API which is relevant to `ros2bag` package in this PR.
It looks like problem on baseline:
Tests failing with the same error messages on all platforms:
```
2022-10-10T22:44:20.2630481Z ============================= test session starts ==============================
2022-10-10T22:44:20.2631068Z platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
2022-10-10T22:44:20.2631580Z cachedir: /__w/rosbag2/rosbag2/ros_ws/build/ros2bag/.pytest_cache
2022-10-10T22:44:20.2632109Z rootdir: /__w/rosbag2/rosbag2/ros_ws/src/gg60q98ux0g/rosbag2/ros2bag, configfile: pytest.ini
2022-10-10T22:44:20.2633219Z plugins: launch-testing-ros-0.21.0, launch-testing-1.2.0, ament-copyright-0.13.2, ament-pep257-0.13.2, ament-flake8-0.13.2, ament-lint-0.13.2, rerunfailures-10.2, cov-4.0.0, mock-3.10.0, colcon-core-0.5.9, repeat-0.9.1, timeout-1.3.3
2022-10-10T22:44:20.2633898Z collected 13 items
2022-10-10T22:44:20.2634541Z 
2022-10-10T22:44:20.2634786Z test/test_api.py ......                                                  [ 46%]
2022-10-10T22:44:20.2635242Z test/test_burst.py .                                                     [ 53%]
2022-10-10T22:44:20.2636015Z test/test_copyright.py .                                                 [ 61%]
2022-10-10T22:44:20.2636576Z test/test_flake8.py F                                                    [ 69%]
2022-10-10T22:44:20.2637151Z test/test_pep257.py .                                                    [ 76%]
2022-10-10T22:44:20.2637571Z test/test_play_qos_profiles.py .                                         [ 84%]
2022-10-10T22:44:20.2637991Z test/test_record.py .                                                    [ 92%]
2022-10-10T22:44:20.2638403Z test/test_record_qos_profiles.py .                                       [100%]
2022-10-10T22:44:20.2638747Z 
2022-10-10T22:44:20.2638996Z =================================== FAILURES ===================================
2022-10-10T22:44:20.2639406Z _________________________________ test_flake8 __________________________________
2022-10-10T22:44:20.2639833Z multiprocessing.pool.RemoteTraceback: 
2022-10-10T22:44:20.2640208Z """
2022-10-10T22:44:20.2640515Z Traceback (most recent call last):
2022-10-10T22:44:20.2641123Z   File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
2022-10-10T22:44:20.2641562Z     result = (True, func(*args, **kwds))
2022-10-10T22:44:20.2642134Z   File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
2022-10-10T22:44:20.2642550Z     return list(map(*args))
2022-10-10T22:44:20.2643166Z   File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 666, in _run_checks
2022-10-10T22:44:20.2643694Z     return checker.run_checks()
2022-10-10T22:44:20.2644258Z   File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 598, in run_checks
2022-10-10T22:44:20.2644777Z     self.run_ast_checks()
2022-10-10T22:44:20.2645504Z   File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 502, in run_ast_checks
2022-10-10T22:44:20.2645989Z     for (line_number, offset, text, check) in runner:
2022-10-10T22:44:20.2646554Z   File "/usr/local/lib/python3.8/dist-packages/flake8_deprecated.py", line 47, in run
2022-10-10T22:44:20.2646975Z     yield from value
2022-10-10T22:44:20.2647524Z   File "/usr/local/lib/python3.8/dist-packages/flake8_deprecated.py", line 57, in check_calls
2022-10-10T22:44:20.2647953Z     yield from value
2022-10-10T22:44:20.2648673Z   File "/usr/local/lib/python3.8/dist-packages/flake8_deprecated.py", line 70, in check_method_call
2022-10-10T22:44:20.2649147Z     method_name = node.func.attr
2022-10-10T22:44:20.2649658Z AttributeError: 'Subscript' object has no attribute 'attr'
2022-10-10T22:44:20.2650025Z """
2022-10-10T22:44:20.2650229Z 
2022-10-10T22:44:20.2650494Z The above exception was the direct cause of the following exception:
2022-10-10T22:44:20.2651085Z test/test_flake8.py:22: in test_flake8
2022-10-10T22:44:20.2651531Z     rc, errors = main_with_errors(argv=[])
2022-10-10T22:44:20.2651953Z ../../../../build/ament_flake8/ament_flake8/main.py:88: in main_with_errors
2022-10-10T22:44:20.2652868Z     report = generate_flake8_report(
2022-10-10T22:44:20.2653726Z ../../../../build/ament_flake8/ament_flake8/main.py:233: in generate_flake8_report
2022-10-10T22:44:20.2654700Z     report.report = style.check_files(paths)
2022-10-10T22:44:20.2655269Z /usr/local/lib/python3.8/dist-packages/flake8/api/legacy.py:100: in check_files
2022-10-10T22:44:20.2655651Z     self._application.run_checks(paths)
2022-10-10T22:44:20.2656727Z /usr/local/lib/python3.8/dist-packages/flake8/main/application.py:300: in run_checks
2022-10-10T22:44:20.2657112Z     self.file_checker_manager.run()
2022-10-10T22:44:20.2657556Z /usr/local/lib/python3.8/dist-packages/flake8/checker.py:329: in run
2022-10-10T22:44:20.2658078Z     self.run_parallel()
2022-10-10T22:44:20.2658618Z /usr/local/lib/python3.8/dist-packages/flake8/checker.py:293: in run_parallel
2022-10-10T22:44:20.2659128Z     for ret in pool_map:
2022-10-10T22:44:20.2659456Z /usr/lib/python3.8/multiprocessing/pool.py:448: in <genexpr>
2022-10-10T22:44:20.2659821Z     return (item for chunk in result for item in chunk)
2022-10-10T22:44:20.2660160Z /usr/lib/python3.8/multiprocessing/pool.py:868: in next
2022-10-10T22:44:20.2660454Z     raise value
2022-10-10T22:44:20.2660868Z E   AttributeError: 'Subscript' object has no attribute 'attr'
2022-10-10T22:44:20.2661380Z --- generated xml file: /__w/rosbag2/rosbag2/ros_ws/build/ros2bag/pytest.xml ---
2022-10-10T22:44:20.2661820Z =========================== short test summary info ============================
2022-10-10T22:44:20.2683588Z FAILED test/test_flake8.py::test_flake8 - AttributeError: 'Subscript' object ...
2022-10-10T22:44:20.2684024Z ======================== 1 failed, 12 passed in 11.82s =========================
```
I can't figure out what is wrong with `ros2bag` package or CI infrastructure.
I have tried to build and run tests for this branch on my local machine and all passes without error.
With one caveat that my local configuration has a bit older **ament-lint-0.13.1** versus **ament-lint-0.13.2** on CI.
It looks like something was recently merged in to the `ament-lint-0.13.2` which is causing tests failure.

2022-10-11 12:10 UTC, clalancette commented
> 2022-10-10T22:44:20.2660868Z E   AttributeError: 'Subscript' object has no attribute 'attr'

There is a bug in recent flake8-deprecated that is causing this.  See https://github.com/ros2/ci/pull/682, which still needs to have CI run on it and merged.

2022-10-11 18:22 UTC, MichaelOrlov commented
@clalancette Thanks for clarification.

2022-10-12 17:35 UTC, MichaelOrlov commented
Trying to re-run CI
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/10972
Building on the built-in node in workspace /var/lib/jenkins/jobs/ci_launcher/workspace
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17480)](http://ci.ros2.org/job/ci_linux/17480/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12008)](http://ci.ros2.org/job/ci_linux-aarch64/12008/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18029)](http://ci.ros2.org/job/ci_windows/18029/)

2022-10-12 20:58 UTC, merged

2022-10-12 22:32 UTC, rshanor commented
@MichaelOrlov thank you for relaunching.
@emersonknapp If possible, I would greatly appreciate this being backported to humble.

2022-10-14 00:09 UTC, emersonknapp commented
@mergifyio backport humble

2022-11-09 23:29 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-10-13/28213/1