Refine root cause of the `unpaused_sleep_returns_true` test failure
ros2/rosbag2 pull request #1367
Opened 2023-06-03 06:36 UTC by MichaelOrlov

- Follow up to the failure in https://ci.ros2.org/job/ci_windows/19597/

2023-06-09 23:58 UTC, emersonknapp approved these changes
:+1: I think we should merge this, and get the extra info for future test failures.

2023-06-10 01:06 UTC, emersonknapp commented
Oh ... `rclcpp::ok()` was _never_ true, ever. Nothing ever calls `rclcpp::init()` in this test suite! In fact, `rclcpp::ok()` is explicitly not a requirement - `TimeControllerClock` only calls a `now_fn`, it doesn't care about `rclcpp` status. The check that was added to the test in https://github.com/ros2/rosbag2/pull/1012/files#diff-ea9ff4b69cd29013d4599d8e20313ab1f1dd918e82e810755dad97abfd9f4a51R161 did exactly nothing, because if the clock has a spurious wakeup then `rclcpp::ok() == false` and the loop exits anyways.

2023-06-10 01:50 UTC, emersonknapp requested changes
Revoking approval since this will never be true

2023-06-10 20:22 UTC, MichaelOrlov commented
- Closing as will not be merged in favor of the #1384

2023-06-10 20:22 UTC, closed without merging