Mark play_end_to_end test as xfail
ros2/rosbag2 pull request #1452
Opened 2023-08-23 19:34 UTC by Crola1702

As mentioned in https://github.com/ros2/rosbag2/issues/1437

2023-08-23 19:36 UTC, Crola1702 commented
CI: 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19380)](http://ci.ros2.org/job/ci_linux/19380/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13904)](http://ci.ros2.org/job/ci_linux-aarch64/13904/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20100)](http://ci.ros2.org/job/ci_windows/20100/)

2023-08-27 18:13 UTC, emersonknapp commented
Should we only do this on windows?

2023-08-28 06:00 UTC, MichaelOrlov requested changes
I think it makes sense to mark the test as xfail only for the Windows platform seems it only regularly fails on Windows.

2023-08-28 06:00 UTC, MichaelOrlov commented on rosbag2_tests/CMakeLists.txt
> +    ament_add_test_label(test_rosbag2_play_end_to_end xfail)
```suggestion
if(WIN32)
    ament_add_test_label(test_rosbag2_play_end_to_end xfail)
endif()
```

2023-08-28 11:34 UTC, Crola1702 commented on rosbag2_tests/CMakeLists.txt
> +    ament_add_test_label(test_rosbag2_play_end_to_end xfail)
Yes you're right. I totally missed that.

2023-08-28 11:38 UTC, Crola1702 commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19399)](http://ci.ros2.org/job/ci_linux/19399/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13928)](http://ci.ros2.org/job/ci_linux-aarch64/13928/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20120)](http://ci.ros2.org/job/ci_windows/20120/)

2023-08-28 12:56 UTC, clalancette approved these changes
Looks reasonable to me, but I'd like to wait for final confirmation from @MichaelOrlov before merging.

2023-08-28 17:37 UTC, MichaelOrlov approved these changes
:+1:

2023-08-28 17:38 UTC, merged

2023-08-28 17:41 UTC, MichaelOrlov commented
@clalancette Sorry, I haven't had a chance yet to make a comprehensive analysis about the reason why this test fails on Windows. But as I said before, I don't mind disabling this test for Windows for a while. Anyway, I will have to reproduce the failure locally.

2023-08-28 17:52 UTC, clalancette commented
> @clalancette Sorry, I haven't had a chance yet to make a comprehensive analysis about the reason why this test fails on Windows. But as I said before, I don't mind disabling this test for Windows for a while. Anyway, I will have to reproduce the failure locally.

No worries at all, thanks for any time you spend on it.  I think disabling it just for Windows is a good compromise for now.