Make `play()` run in a separate thread (#1500)
ros2/rosbag2 pull request #1503
Opened 2023-11-26 13:33 UTC by roncapat

This in intended to solve the issue reported in #1500.
CC: @MichaelOrlov @KenYN

This can be also beneficial introductory work for #1419. As it has been noticed, playback shall start automatically when the `Player` component is loaded, but this can't be done via syncronous call by the component constructor.

2023-11-27 01:19 UTC, KenYN commented
I did `git checkout patch-2 && git merge roncagliolo/async-play` and it appears to be operating correctly, although by no means is this a thorough test, but thank you very much for this.

2023-11-29 01:11 UTC, MichaelOrlov requested changes
@roncapat See my suggestions for review fixes in the https://github.com/roncapat/rosbag2/pull/6 PR

2023-11-29 06:47 UTC, roncapat commented
@MichaelOrlov review branch merged :)

2023-11-29 08:16 UTC, MichaelOrlov approved these changes
LGTM

2023-11-29 08:19 UTC, MichaelOrlov commented
Gist: https://gist.githubusercontent.com/MichaelOrlov/aa32bdbe242c8c06daca683655e76bb4/raw/4be47e99df1fdad56dd18ce5f2d2c4f04ff13980/ros2.repos
BUILD args:  --packages-above-and-dependencies rosbag2_transport rosbag2_tests rosbag2_py
TEST args:  --packages-above rosbag2_transport rosbag2_tests rosbag2_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12985
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19896)](http://ci.ros2.org/job/ci_linux/19896/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14380)](http://ci.ros2.org/job/ci_linux-aarch64/14380/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20603)](http://ci.ros2.org/job/ci_windows/20603/)

2023-11-29 16:14 UTC, merged

2023-11-29 17:00 UTC, MichaelOrlov commented
https://github.com/Mergifyio backport iron

2023-11-29 17:17 UTC, MichaelOrlov commented
Note:
Backporting to the Iron and Humble is not possible because It will cause ABI-breaking changes.
-  it requires adding new member variables to the Player class and we don't have `pimpl` design for the Player class on the Iron and Humble branches.