Added exclude-topic-types to record
ros2/rosbag2 pull request #1582
Opened 2024-03-12 13:01 UTC by ahcorde

Same idea as this PR https://github.com/ros2/rosbag2/pull/1577 but in this case exclude by topic type

build on top of the mentioned PR

2024-03-14 20:25 UTC, MichaelOrlov commented
- This PR needs to be rebased above https://github.com/ros2/rosbag2/pull/1585

2024-03-14 23:13 UTC, fujitatomoya commented
@ahcorde after the rebase, i am happy to review this.

2024-03-18 13:25 UTC, ahcorde commented
> @ahcorde after the rebase, i am happy to review this.

@fujitatomoya ready for review

2024-03-18 17:31 UTC, fujitatomoya approved these changes
implementation looks good to me.

@ahcorde could you share your use case for these `include` and `exclude` topic types?

IMO, currently we can have topic with single type, right? so having the topic options would be good enough for the user configuration. are these extended options for supporting multiple types on a single topic? so that user can filter the specific topic types for the topic? i am curious about the use case. thanks in advance.

2024-03-19 10:21 UTC, ahcorde commented
@fujitatomoya 

Imaging that I have a decent amount of cameras running and I just want to avoid include all of them, with the exclude topic types, it's quite easy to do it, then I can analize my data easily

And the opposite for the other argument, I have a lot topics publishing but I only want to record my cameras, because I want to rerun my algorithm based on cameras.

does it make sense ?

2024-03-20 08:54 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20506)](http://ci.ros2.org/job/ci_linux/20506/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14905)](http://ci.ros2.org/job/ci_linux-aarch64/14905/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21254)](http://ci.ros2.org/job/ci_windows/21254/)

2024-03-20 21:51 UTC, ahcorde commented
@MichaelOrlov are you fine with this PR ?

2024-03-22 08:55 UTC, ahcorde commented
@ros-pull-request-builder retest this please

2024-03-25 15:15 UTC, ahcorde commented
friendly ping @MichaelOrlov

2024-03-26 07:21 UTC, MichaelOrlov commented
@ahcorde Sorry for the delay. Was busy with other PRs and issues. 
I will take a look tomorrow.

2024-03-27 07:08 UTC, MichaelOrlov commented
@ahcorde I see some changes in the API in the `rosbag2_py` package.
Could you please rebase your branch and regenerate Python stubs according to the instruction from the https://github.com/ros2/rosbag2/blob/rolling/rosbag2_py/README.md ?
We recently merged  [Add Python stubs for rosbag2_py #1569](https://github.com/ros2/rosbag2/pull/1569) and now require updating Python stubs.

2024-03-27 07:27 UTC, MichaelOrlov requested changes
@ahcorde Overall looks good among one finding in tests and one nitpick.

2024-03-27 07:27 UTC, MichaelOrlov commented on rosbag2_transport/src/rosbag2_transport/topic_filter.cpp
> +
```suggestion
    if (topic_type_in_list(topic_type, record_options_.exclude_topic_types))
    {
      return false;
    }

```
Don't need to check for an empty vector. The `topic_type_in_list(..)` efficiently handles the use case if the list is empty.

2024-03-27 07:27 UTC, MichaelOrlov commented on rosbag2_transport/test/rosbag2_transport/test_topic_filter.cpp
> +
```suggestion

  EXPECT_TRUE(filtered_topics.find("/localization") == filtered_topics.end());
  EXPECT_TRUE(filtered_topics.find("/status") == filtered_topics.end());
```
Please add check that the filter really excludes topics by types.

2024-03-27 17:34 UTC, MichaelOrlov approved these changes
@ahcorde Thanks. LGTM with green CI.

2024-03-27 17:44 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20624)](http://ci.ros2.org/job/ci_linux/20624/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14976)](http://ci.ros2.org/job/ci_linux-aarch64/14976/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21349)](http://ci.ros2.org/job/ci_windows/21349/)

2024-03-27 22:05 UTC, MichaelOrlov commented
@ahcorde Please hold off from merging. Let's merge the release first https://github.com/ros2/rosbag2/pull/1596 since it has already in progress.

2024-03-28 10:49 UTC, merged