Update sqlite-amalgamation into CMakeLists.txt
ros2/rosbag2 pull request #1611
Opened 2024-04-16 00:55 UTC by mosfet80

Update sqlite-amalgamation

2024-04-16 00:59 UTC, clalancette requested changes

2024-04-16 00:59 UTC, clalancette commented on sqlite3_vendor/CMakeLists.txt
> +  VCS_VERSION ssqlite-amalgamation-3450300
Changing the URL here is suspicious. This should remain sqlite.org .  Also, there is a typo in that there should only be one `s` in the VCS_VERSION.

2024-04-16 16:13 UTC, MichaelOrlov requested changes

2024-04-16 16:13 UTC, MichaelOrlov commented on sqlite3_vendor/CMakeLists.txt
> +  VCS_URL https://www.sqlite.com/2024/sqlite-amalgamation-3450300.zip
As @clalancette already mentioned, the link should point to the www.sqlite.org 
```suggestion
  VCS_URL https://www.sqlite.org/2024/sqlite-amalgamation-3450300.zip
```

2024-04-28 02:13 UTC, MichaelOrlov requested changes
@mosfet80 Thank you for addressing our comments per review. LGTM.
Could you please fix DCO?
https://github.com/ros2/rosbag2/pull/1611/checks?check_run_id=24298443545

2024-05-01 00:52 UTC, MichaelOrlov commented
@mosfet80 Friendly ping here to fix DCO in this PR.

2024-06-08 01:37 UTC, MichaelOrlov commented
@r7vme May I ask you to pick up this PR?
This PR became stale without a response from the author for a long time. However, it would be good to have changes from this PR in our code base. I would propose creating a new PR and cherry-picking changes from this PR with mentioning co-authoring with the author of this PR and get it throw review, approval and finally merge it.

2024-06-29 00:12 UTC, christophebedard commented on sqlite3_vendor/CMakeLists.txt
> +  VCS_VERSION sqlite-amalgamation-3450300
The version from Ubuntu Noble is 3.45.1, so I think this should be:

```suggestion
  VCS_URL https://www.sqlite.org/2024/sqlite-amalgamation-3450100.zip
  VCS_VERSION sqlite-amalgamation-3450100
```

The `sqlite3.h` header in the ZIP file indeed shows version `3.45.1`.

2024-06-29 00:21 UTC, christophebedard commented on sqlite3_vendor/CMakeLists.txt
> +  VCS_VERSION sqlite-amalgamation-3450300
I've made these changes in #1737

2024-06-29 00:58 UTC, MichaelOrlov commented
- Closing as stale PR in favor of the #1737

2024-06-29 00:58 UTC, closed without merging