[humble] Add --log-level to ros2 bag play and record
ros2/rosbag2 pull request #1655
Opened 2024-05-13 12:22 UTC by r7vme

Backport of https://github.com/ros2/rosbag2/pull/1625

2024-05-13 15:37 UTC, fujitatomoya approved these changes
lgtm, i will start the CI.

2024-05-13 15:39 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21061)](http://ci.ros2.org/job/ci_linux/21061/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15365)](http://ci.ros2.org/job/ci_linux-aarch64/15365/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21777)](http://ci.ros2.org/job/ci_windows/21777/)

2024-05-13 16:40 UTC, MichaelOrlov requested changes
There are some linter warnings which need to be addressed.

2024-05-14 11:18 UTC, r7vme commented
@MichaelOrlov there was missing `import pytest`. Fixed

2024-05-14 14:45 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21080)](http://ci.ros2.org/job/ci_linux/21080/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15383)](http://ci.ros2.org/job/ci_linux-aarch64/15383/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21797)](http://ci.ros2.org/job/ci_windows/21797/)

2024-05-14 15:54 UTC, MichaelOrlov approved these changes
LGTM with green CI.

2024-05-14 18:39 UTC, merged