Update sqlite
ros2/rosbag2 pull request #1785
Opened 2024-08-10 07:11 UTC by mosfet80

Allocate additional memory from the heap for the SQL parser stack if that stack overflows, rather than reporting a "parser stack overflow" error.

Complete change list::
https://www.sqlite.org/releaselog/3_46_0.html

2024-08-19 14:59 UTC, fujitatomoya approved these changes
lgtm with green CI

2024-08-19 15:06 UTC, clalancette requested changes
As with other vendored packages, I'd prefer to keep this the same as the version in Ubuntu 24.04, which is 3.45.1 (the version already vendored here).  So I don't think we should take this at this time.

2024-08-19 15:22 UTC, fujitatomoya commented
@clalancette Ah okay, that is the the policy basically. (unless something comes up) i did not know that, thanks!

2024-08-20 20:24 UTC, MichaelOrlov commented
- Closing as will not be merged with explanation in the https://github.com/ros2/rosbag2/pull/1785#pullrequestreview-2245807674

2024-08-20 20:24 UTC, closed without merging