Removed warnings
ros2/rosbag2 pull request #1794
Opened 2024-08-27 15:59 UTC by ahcorde

There are some new warnings on clang https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1993/gcc/new/folder.1817012694/

2024-08-27 15:59 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21749)](http://ci.ros2.org/job/ci_linux/21749/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16024)](http://ci.ros2.org/job/ci_linux-aarch64/16024/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1254)](http://ci.ros2.org/job/ci_linux-rhel/1254/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22452)](http://ci.ros2.org/job/ci_windows/22452/)

2024-08-27 16:07 UTC, clalancette requested changes
Arg.  We can't do this because this won't compile on MSVC; see https://github.com/ros2/rosbag2/pull/1792#pullrequestreview-2257605434 .

I think the best we can do here is switch the `expected_messages` back to just a `const size_t`, and then keep the captures.  I think that should make both Windows and Clang happy.

2024-08-27 16:49 UTC, fujitatomoya reviewed
Just idea, how about adding `static` to share the `expected_messages` compiled ROM data in the function to remove the capture?

2024-08-28 08:47 UTC, ahcorde commented
@clalancette and @fujitatomoya  what about this solution ? I used a similar approach in other similar cases like this one https://github.com/ros2/geometry2/pull/682/files

2024-08-28 09:29 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21753)](http://ci.ros2.org/job/ci_linux/21753/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16028)](http://ci.ros2.org/job/ci_linux-aarch64/16028/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1259)](http://ci.ros2.org/job/ci_linux-rhel/1259/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22455)](http://ci.ros2.org/job/ci_windows/22455/)

2024-08-28 15:54 UTC, fujitatomoya approved these changes
lgtm with green CI

2024-08-28 16:05 UTC, clalancette commented
Here's also a Clang run to ensure that this fixes it on Clang:

* Clang [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux_clang_libcxx&build=77)](http://ci.ros2.org/job/ci_linux_clang_libcxx/77/)

2024-08-28 18:29 UTC, clalancette approved these changes

2024-08-28 18:29 UTC, merged

2024-09-17 23:53 UTC, MichaelOrlov commented
https://github.com/Mergifyio backport jazzy