Handle transient local messages in snapshot mode when the buffer is full
ros2/rosbag2 pull request #1887
Opened 2024-12-23 09:58 UTC by doisyg

Draft to discuss ways of solving https://github.com/ros2/rosbag2/issues/1886

Naive solution which throws away the first message that is not transient local when the buffer is full, as long as the number of messages at the beginning of the buffer accounts for less than 10% of the total number of messages in the buffer.

That will not solve completely the `/tf_static` use case if other transient local messages are recorded and periodically published: at some point there will be more than 10% of transient local messages in the buffer, and the first ones (i.e `/tf_static`) will be removed.

Interested in debating and suggestions on how to solve this properly :
- Different buffers for each transient local topic ? But then how to control their max size ?
- A buffer dedicated to `/tf_static`? But then loss of generality.
- Something else ?

2024-12-23 16:06 UTC, doisyg commented
(PR non functional for Rolling, I was originally targeting Iron, will fix)

2025-01-10 02:41 UTC, MichaelOrlov commented
@doisyg The transient local messages usually appear somewhere at the beginning of the recording like `/tf_static`. 
It seems make sense to consider adding an option for repeating some number of the transient local messages for each new recording bag rather than throwing away some percentage of the messages.  
I have formulated a design proposal in another task https://github.com/ros2/rosbag2/issues/1159#issuecomment-2183281437. Please take it into consideration.

2025-12-15 17:25 UTC, tonynajjar commented
> @doisyg The transient local messages usually appears somewhere at the beginning of the recording like `/tf_static`. It seems make sense to consider adding an option for repeating some number of the transient local messages for each new recording bag rather than throwing away some percentage of the messages. I have formulated a design proposal in another task [#1159 (comment)](https://github.com/ros2/rosbag2/issues/1159#issuecomment-2183281437). Please take it into consideration.

@MichaelOrlov are you sure that your proposal would also solve what this PR is trying to solve? The bug described in the ticket has nothing to do with splitting, you can reproduce by:

1- Starting a a bag in snapshot with a relatively low --max-cache-size. It should record `tf_static` along with other topics
2- Publish a transient local topic, like `/tf_static`
3- Publish enough so that the bag size exceeds --max-cache-size
4- Call the snapshot service
5- See that /tf_static topic is not in the bag

Do you have any proposal to fix or workaround that?

2025-12-22 08:19 UTC, MichaelOrlov commented
@tonynajjar As from my other comment https://github.com/ros2/rosbag2/issues/1159#issuecomment-2902812644
The additional CLI options would be 
```bash
$ ros2 bag record -a --repeat-latched /map=1 /tf_static=5
```

For snapshot mode, the straightforward approach would be to keep "latched" messages in a separate buffer and dump it to the disk before the circular buffer with other messages. Trying to reduce the circular buffer on a fly when latched mesages arrives seems is non-trivial. The feature would be more consistent with another feature for snapshot https://github.com/ros2/rosbag2/pull/1844 to limit the bag file by duration rather than by bag size.

2026-02-07 09:14 UTC, MichaelOrlov requested changes
Hi @tonynajjar, I've finally found a time for review and more thorough consideration about how to gracefully handle the repetition of the transient-local messages during recording in general.

First of all, I would like to say you a big thank you for the prototyping and your attempt to solve this complicated task.
Although I found that your design approach is not suitable for the cases when we need to do a regular bag split, and is not capable of handling some corner cases like message duplicates in the snapshot buffer and transient-local buffer as well as some performance aspects and concurrency.

I've gone ahead and spent some substantial time creating a design document https://github.com/ros2/rosbag2/pull/2327 for this transient-local (“latched”) messages in Rosbag2 recorder feature. I would encourage you to read it and participate in the review.

2026-02-07 09:28 UTC, tonynajjar commented
Hi @MichaelOrlov , thanks for jumping on that! No worries about my PR, I'm pretty sure it's not the cleanest one conceptually and architecturally - I just needed something quick to fix our issue and kickstart the discussion with a practical first step.
I'll take a look next week at what you came up with!

2026-04-02 16:07 UTC, MichaelOrlov commented
- Closing thi PR in favor of the 
- https://github.com/ros2/rosbag2/pull/2385
- https://github.com/ros2/rosbag2/pull/2386
- https://github.com/ros2/rosbag2/pull/2387

2026-04-02 16:07 UTC, closed without merging