[ros2bag test_record] Gets rid of time.sleep and move to using NamedTemporaryFile
ros2/rosbag2 pull request #525
Opened 2020-09-17 17:19 UTC by jaisontj

Tries to fix #454 

Looks to me that the original problem described at #454 was probably addressed by #466 
However, before #466, there was #462 which moved from using different temp directory per test to using one temp directory for all the tests - this PR also introduced the time.sleeps within each test and also one within the cleanup block (which deletes the temp directory)

In this PR; I've moved to using `NamedTemporaryFile` for each test - this has the advantage of not having to manually clean up the files after since the test runs within the context manager. Moreover, I was also able to replace all of the time.sleep within each of the tests and have the tests pass locally.

2020-09-18 17:59 UTC, jaisontj commented
Each of the tests can also be reduced to:

```python
 def test_nonexistent_qos_profile(self):
        profile_path = PROFILE_PATH / 'foobar.yaml'
        output_path = Path(self.tmpdir.name) / 'ros2bag_test_nonexistent'
        arguments = ['record', '-a', '--qos-profile-overrides-path', profile_path.as_posix(),
                     '--output', output_path.as_posix()]
        expected_string_regex = re.compile(
            r'ros2 bag record: error: argument --qos-profile-overrides-path: can\'t open')
        with self.launch_bag_command(arguments=arguments) as bag_command:
            condition_result = bag_command.wait_for_output(
                condition=lambda output: expected_string_regex.search(output) is not None,
                timeout=5)
            assert condition_result, print('ros2bag CLI did not produce the expected output')
        bag_command.wait_for_shutdown(timeout=5)
        assert bag_command.terminated
        assert bag_command.exit_code != launch_testing.asserts.EXIT_OK
```

However, this can have an edge case where `wait_for_command` gets called after the expected string is printed out.

2020-09-18 20:42 UTC, dabonnie requested changes
Were you able to run the tests repeatedly by any chance?

2020-09-18 20:42 UTC, dabonnie commented on ros2bag/test/test_record_qos_profiles.py
> +                timeout=5)
Defining the timeout would be nice since it's reused (no magic numbers).

2020-09-18 20:42 UTC, dabonnie commented on ros2bag/test/test_record_qos_profiles.py
> +        assert matches, print('ros2bag CLI did not produce the expected output')
In each case can you also print the error output?

2020-09-21 16:46 UTC, jaisontj commented
> Were you able to run the tests repeatedly by any chance?

I've been testing on windows using: `colcon test --packages-select ros2bag --retest-until-fail 25 --merge-install`

2020-09-21 16:48 UTC, jaisontj commented
Looks like the build failure on `Rpr__rosbag2__ubuntu_focal_amd64` is unrelated to this PR as the associated tests have passed: http://build.ros2.org/job/Rpr__rosbag2__ubuntu_focal_amd64/206/console#console-section-5

2020-09-21 18:53 UTC, jaisontj commented
Running on CI: 

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12377)](http://ci.ros2.org/job/ci_linux/12377/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7346)](http://ci.ros2.org/job/ci_linux-aarch64/7346/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10089)](http://ci.ros2.org/job/ci_osx/10089/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12289)](http://ci.ros2.org/job/ci_windows/12289/)

2020-09-21 20:27 UTC, jaisontj commented
CI On windows with --retest-until-fail 25

* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12294)](http://ci.ros2.org/job/ci_windows/12294/)

2020-09-21 21:52 UTC, jaisontj commented
Do note that I was unable to get rid  of the `time.sleep` [here](https://github.com/ros2/rosbag2/blob/6e9d96659bb571d12a0d5b9ebdb293a884bed5e0/ros2bag/test/test_record_qos_profiles.py#L79) as this hack seems to be required.

2020-09-21 23:48 UTC, dabonnie approved these changes

2020-09-22 19:20 UTC, emersonknapp approved these changes
LGTM!

2020-09-22 20:18 UTC, jikawa-az approved these changes

2020-09-22 23:53 UTC, merged