Expose the QoS object wrapper
ros2/rosbag2 pull request #910
Opened 2021-11-11 04:02 UTC by gbiggs

This PR exposes the QoS wrapper in `rosbag_transport` for use by external users. This enables users of rosbag2 to create their own `recorder` objects that mimic the behaviour of the provided `Recorder` object with regards to QoS.

2021-11-12 00:00 UTC, MichaelOrlov approved these changes
Looks good for me with green CI.

2021-11-12 04:22 UTC, MichaelOrlov commented
Running CI
Gist: https://gist.githubusercontent.com/MichaelOrlov/83f9321f21d3e3f335e590b56aadbfdf/raw/f9d6343b8c9671d97c868ffc3c5689e8990fce87/ros2.repos
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages_select rosbag2_transport rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9337/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15602)](http://ci.ros2.org/job/ci_linux/15602/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10284)](http://ci.ros2.org/job/ci_linux-aarch64/10284/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13267)](http://ci.ros2.org/job/ci_osx/13267/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15819)](http://ci.ros2.org/job/ci_windows/15819/)

2021-11-12 07:00 UTC, MichaelOrlov commented
Ups. I made mistake in gist.
Rerunning CI one more time
Gist: https://gist.githubusercontent.com/MichaelOrlov/83f9321f21d3e3f335e590b56aadbfdf/raw/b4a57608e47b583465cc965a2f53fdbad86e4d49/ros2.repos
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages_select rosbag2_transport rosbag2_tests
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9338/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15603)](http://ci.ros2.org/job/ci_linux/15603/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10285)](http://ci.ros2.org/job/ci_linux-aarch64/10285/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13268)](http://ci.ros2.org/job/ci_osx/13268/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15820)](http://ci.ros2.org/job/ci_windows/15820/)

2021-11-12 07:26 UTC, MichaelOrlov commented
Something weird happening on CI. It looks like some problems with `ccache`.
CI reports some errors in test `urdfdom_headers` 
```
Starting >>> urdfdom_headers
23:10:42 Traceback (most recent call last):
23:10:42   File "/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.8/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
23:10:42     rc = await self.task(*args, **kwargs)
23:10:42   File "/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.8/site-packages/colcon_core/task/__init__.py", line 93, in __call__
23:10:42     return await task_method(*args, **kwargs)
23:10:42   File "/home/jenkins-agent/workspace/ci_linux/venv/lib/python3.8/site-packages/colcon_cmake/task/cmake/test.py", line 45, in test
23:10:42     assert os.path.exists(args.build_base), \
23:10:42 AssertionError: Has this package been built before?
```
This package present in Gist ros2.repos and it looks like that CI expecting to take it from `ccache` but it seems it's not there.

2021-11-12 07:36 UTC, MichaelOrlov commented
Trying to rerun CI
Gist: https://gist.githubusercontent.com/MichaelOrlov/83f9321f21d3e3f335e590b56aadbfdf/raw/b4a57608e47b583465cc965a2f53fdbad86e4d49/ros2.repos
BUILD args: --packages-up-to rosbag2_cpp rosbag2_transport rosbag2_tests rosbag2
TEST args: --packages-select rosbag2_cpp rosbag2_transport rosbag2_tests rosbag2
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9339/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15604)](http://ci.ros2.org/job/ci_linux/15604/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10286)](http://ci.ros2.org/job/ci_linux-aarch64/10286/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13270)](http://ci.ros2.org/job/ci_osx/13270/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15821)](http://ci.ros2.org/job/ci_windows/15821/)

2021-11-12 19:38 UTC, MichaelOrlov requested changes
@gbiggs I see some linker errors on Windows platform https://ci.ros2.org/job/ci_windows/15821/console#console-section-13. 
Could you please take a look on it?

2021-11-15 20:57 UTC, emersonknapp commented on rosbag2_transport/include/rosbag2_transport/qos.hpp
> +  ROSBAG2_TRANSPORT_PUBLIC
I think you might be able to achieve this with just `class ROSBAG2_TRANSPORT_PUBLIC Rosbag2QoS` instead of marking all methods. Feels tidier to me

2021-11-15 20:58 UTC, emersonknapp approved these changes
Looks good though - take tidiness nitpick if you like

2021-11-15 23:33 UTC, gbiggs commented
I changed the export to be on the class rather than the individual methods. @MichaelOrlov maybe this will fix those linker errors? I don't have any experience with Windows linking more recent than 20 years ago.

2021-11-16 21:39 UTC, MichaelOrlov commented
@gbiggs I am also not an expert Windows platform and don't have local install of the ROS build environment on Windows.
However I spawned rerun for Windows build on CI to see if it will pass with your latest changes.
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15835)](http://ci.ros2.org/job/ci_windows/15835/)

2021-11-17 00:16 UTC, gbiggs commented
The linker errors are still happening, but I can't figure out why. @emersonknapp do you have any ideas?

2021-11-22 22:12 UTC, emersonknapp commented
I think it was from some outdated CMake workarounds, from before qos.hpp was exposed for use. The new visibility macros made it so that `test_qos` declared as `dllimport`, while actually defining the functions within the same shared library, causing a mismatch. By removing that source file from the test library, I believe that gets rid of the problem.

Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15854)](https://ci.ros2.org/job/ci_windows/15854/)

2021-11-22 22:15 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/ac55fdc23ec56ceadaeef4b401da616b/raw/a4b2a884c7a896a710454ad8a5d6a4df94fd0822/ros2.repos
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9369
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15636)](http://ci.ros2.org/job/ci_linux/15636/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10316)](http://ci.ros2.org/job/ci_linux-aarch64/10316/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13304)](http://ci.ros2.org/job/ci_osx/13304/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15855)](http://ci.ros2.org/job/ci_windows/15855/)

2021-11-22 23:24 UTC, emersonknapp commented
At least that exposed a new issue:

Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15856)](https://ci.ros2.org/job/ci_windows/15856/)

2021-11-23 01:27 UTC, emersonknapp commented
Had to remove the source file from another test [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15858)](https://ci.ros2.org/job/ci_windows/15858/)

2021-11-23 16:38 UTC, emersonknapp commented
I wish I had a repeatable Windows environment but haven't been able to figure that out - Docker on Windows is so hard to set up. This is a bit of a hassle: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15859)](https://ci.ros2.org/job/ci_windows/15859/)

2021-11-23 19:03 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/b7c9052c91d5e019c0bb348d3cbb28a8/raw/a4b2a884c7a896a710454ad8a5d6a4df94fd0822/ros2.repos
BUILD args: --packages-up-to rosbag2_transport rosbag2_tests
TEST args: --packages-select rosbag2_transport rosbag2_tests
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/9375
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15642)](http://ci.ros2.org/job/ci_linux/15642/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10322)](http://ci.ros2.org/job/ci_linux-aarch64/10322/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13310)](http://ci.ros2.org/job/ci_osx/13310/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15865)](http://ci.ros2.org/job/ci_windows/15865/)

2021-11-23 19:55 UTC, merged