Make peek_next_message_from_queue return a SharedPtr.
ros2/rosbag2 pull request #993
Opened 2022-04-20 12:27 UTC by clalancette

It is unsafe to return a pointer to a SharedPtr here,
and then store it; if another thread comes along and
pops the queue, then we are now holding a pointer to an
object that has been freed.  Instead, dereference the
pointer so we get a SharedPtr (and a reference) immediately,
which ensures that the object won't be destroyed if we
race with another thread.

While I was in here, did a small refactoring of the method
to remove some duplicated code.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

Before this PR, if I ran the `test_play_seek` test in a loop with stress on my machine, it would crash every once in a while.  After this PR, I no longer see that crash.  This should fix at least one of the flaky tests on the buildfarm.

2022-04-20 12:28 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16576)](http://ci.ros2.org/job/ci_linux/16576/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11160)](http://ci.ros2.org/job/ci_linux-aarch64/11160/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16964)](http://ci.ros2.org/job/ci_windows/16964/)

2022-04-21 00:03 UTC, gbiggs approved these changes

2022-04-21 05:53 UTC, MichaelOrlov requested changes
@clalancette Thank you for the code clean up.
I agree that using shared pointer instead of pointer to the shared pointer will make code less error prone for the race conditions.

Although I disagree with renaming `message_ptr` to the `message` where its corresponds to the shared pointer. It's still a pointer and comparison aka `message != null_ptr` looks very odd in this case.
Could you please revert such renaming?

2022-04-21 12:06 UTC, clalancette commented
> Although I disagree with renaming `message_ptr` to the `message` where its corresponds to the shared pointer. It's still a pointer and comparison aka `message != null_ptr` looks very odd in this case. Could you please revert such renaming?

I'll point out that the the current naming is following what was already there.  That is, in all cases where we were returning a `SharedPtr *` before, that was stored in a `message_ptr`, and then the dereferenced version (`SharedPtr`) was stored in a `message`.

That said, I'll go in and rename things to `message_ptr`, but I'm also going to rename the variable inside of `peek_next_message_from_queue` to `message_ptr_ptr`.

2022-04-21 12:24 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16586)](http://ci.ros2.org/job/ci_linux/16586/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11168)](http://ci.ros2.org/job/ci_linux-aarch64/11168/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16972)](http://ci.ros2.org/job/ci_windows/16972/)

2022-04-21 14:07 UTC, ivanpauno approved these changes
LGTM!

2022-04-21 15:07 UTC, clalancette commented
The CI failure on Linux is one of the known flaky tests in rosbag2, i.e. test_play_services sometimes just fails.  That's the next one for me to look into.

2022-04-21 15:27 UTC, merged